contacts_web_app/contacts/urls.py
from django.urls import path
from contacts import views

app_name = 'contacts'

urlpatterns = [
    path('', views.main, name='main'),
    path('contacts', views.contacts, name='contacts'),
    path('sort', views.sort, name='sort'),
    path('birthday', views.birthday, name='birthday'),
    path('contacts/edit/<int:contact_id>', views.edit, name='edit'),
    path('delete/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('search_contact', views.search_contact, name='search_contact'),
    path('file_uploader', views.file_uploader, name='file_uploader'),
]

contacts_web_app/contacts_web_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('users.urls', namespace='default')),
    path('users/', include('users.urls')),
    path('notes/', include('notes.urls')),
    path('file_manager/', include('file_manager.urls')),
    path('contacts/', include('contacts.urls')),
    path('news/', include('news.urls')),
    path('adminconsole/', include('adminconsole.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts_web_app/news/urls.py
from django.urls import path

from .views import home, news_war, news_war_show_one, news_prosport, news_prosport_show_one, war_statistic, when_bored


app_name = "news"

urlpatterns = [
    path('', home, name='home'),
    path('news_war/', news_war, name='news_war'),
    path('news_war/<int:_id>', news_war_show_one, name='news_war_show_one'),
    path('news_prosport/', news_prosport, name='news_prosport'),
    path('news_prosport/<int:_id>', news_prosport_show_one, name='news_prosport_show_one'),
    path('war_statistic/', war_statistic, name='war_statistic'),
    path('bored/', when_bored, name='when_bored'),
]

contacts_web_app/contacts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.


class File(models.Model):
    file = models.FileField(upload_to='files')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.file}'


class Contacts(models.Model):
    firstname = models.CharField(max_length=50, null=False)
    lastname = models.CharField(max_length=50, null=False)
    phone = PhoneNumberField()
    email = models.EmailField(null=False, default="example@email.com")
    birthday = models.CharField(max_length=15, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.firstname}, {self.lastname}, {self.phone}, {self.email}, {self.birthday}'

contacts_web_app/contacts/forms.py
from django.forms import TextInput, CharField, ModelForm, EmailField, EmailInput, DateField, DateInput, \
    SelectDateWidget, FileField
from .models import Contacts, File
from phonenumber_field.formfields import PhoneNumberField, RegionalPhoneNumberWidget
from phonenumber_field.widgets import PhoneNumberPrefixWidget

YEARS = [x for x in range(1940, 2020)]


class ContactForm(ModelForm):
    firstname = CharField(min_length=3, max_length=25, required=True,
                          widget=TextInput(attrs={'placeholder': 'Firstname', 'class': "form-control me-2"}))
    lastname = CharField(min_length=3, max_length=25, required=True,
                         widget=TextInput(attrs={'placeholder': 'Lastname', 'class': "form-control me-2"}))
    phone = PhoneNumberField(initial='Ukraine', region='UA',
                             widget=PhoneNumberPrefixWidget(
                                 attrs={'placeholder': 'Phone Number', 'class': "form-control me-2", }))
    email = EmailField(max_length=150, initial="example@email.com",
                       widget=EmailInput(attrs={'placeholder': 'Email', 'class': "form-control me-2"}))
    birthday = DateField(required=True, widget=SelectDateWidget(years=YEARS, attrs={'class': "form-control me-2"}))

    class Meta:
        widgets = {
            'phone': PhoneNumberPrefixWidget(),
        }
        model = Contacts
        fields = ['firstname', 'lastname', 'phone', 'email', 'birthday']

contacts_web_app/contacts/views.py
import csv
import os
from io import TextIOWrapper

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from .forms import ContactForm
from .models import Contacts, File
from datetime import date, datetime, timedelta
from django.contrib import messages

from users.models import Avatar


def main(request):
    """
    The main function is the main page of the contacts app.
    It displays all contacts for a user, if they are logged in.
    If not, it displays an error message.

    :param request: Get the current user
    :return: A list of contacts
    :doc-author: Trelent
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    contacts = Contacts.objects.filter(user=request.user).all().order_by('id') if request.user.is_authenticated else []
    contacts_per_page = 15
    paginator = Paginator(contacts, contacts_per_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'contacts/index.html',
                  context={'contacts': contacts, 'user': request.user, 'page': page, 'avatar': avatar})


@login_required
def search_contact(request):
    """
    The search_contact function is used to search for a contact in the database.
    It takes a request as an argument and returns the searched contacts if they exist.

    :param request: Get the request object from the browser
    :return: The search_contact
    :doc-author: Trelent
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    if request.method == 'POST':
        searched = request.POST['searched']
        if len(searched) > 1:
            contacts = Contacts.objects.filter(firstname__contains=searched,
                                               user=request.user).all() | Contacts.objects.filter(
                lastname__contains=searched, user=request.user).all() | Contacts.objects.filter(
                email__contains=searched, user=request.user).all()
            return render(request, 'contacts/search_contact.html',
                          context={'searched': searched, 'contacts': contacts, 'avatar': avatar})
        return redirect(to='contacts:main')
    else:
        return render(request, 'contacts/search_contact.html')


@login_required
def birthday(request):
    """
    The birthday function is used to display the contacts that have a birthday in the next 7 days.
    It takes request as an argument and returns a render of the birthday template with context containing:
    current_day, which is today's year;
    birthday_list, which contains all contacts that have birthdays in the next 7 days;
    today, which is today's date;
    show, an empty list for use later on when we add search functionality to this page (see below); and avatar.

    :param request: Get the current user
    :return: The list of contacts whose birthday is in the next 7 days
    :doc-author: Trelent
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    contacts_all = Contacts.objects.all()
    current_year = date.today().year
    birthday_list = []
    show = []
    for i in contacts_all:
        if date.today() <= (datetime.strptime(i.birthday.strip('\t'), '%Y-%m-%d').date().replace(
                year=current_year)) < date.today() + timedelta(7):
            birthday_list.append(i)
    return render(request, 'contacts/birthday.html',
                  context={'current_day': current_year, 'birthday_list': birthday_list, 'today': date.today(),
                           'show': show, 'avatar': avatar})


@login_required
def contacts(request):
    """
    The contacts function is used to create a new contact.
        It takes the request as an argument and returns a rendered template with the form.
        If the request method is POST, it will validate and save the data from that form.

    :param request: Get the request object
    :return: The contact page with the form and avatar
    :doc-author: Trelent
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    if request.method == 'POST':
        form = ContactForm(request.POST, )
        if form.is_valid():
            contacts = form.save(commit=False)
            contacts.user = request.user
            contacts.save()
            messages.success(request, "Contact was  created successfully !")
            return redirect(request.META['HTTP_REFERER'])
        else:
            return render(request, 'contacts/contact.html', {'form': form, 'avatar': avatar})
    return render(request, 'contacts/contact.html', {'form': ContactForm(), 'avatar': avatar})


@login_required
def delete_contact(request, contact_id):
    """
    The delete_contact function is called when the user clicks on the delete button
    on a contact's page. It deletes that contact from the database and redirects to
    the main contacts page.

    :param request: Get the user from the request object
    :param contact_id: Find the contact to delete
    :return: A redirect to the main page
    :doc-author: Trelent
    """
    Contacts.objects.get(pk=contact_id, user=request.user).delete()
    return redirect(request.META['HTTP_REFERER'])


@login_required
def edit(request, contact_id):
    """
    The edit function is used to edit a contact.
        It takes the request and contact_id as parameters,
        then it gets the avatar of the user,
        then it gets the contact with that id and for that user,
        then it creates a form using ContactForm class with instance=contact (to fill in fields),
            if this form is valid: save changes to database and redirect to main page.

    :param request: Get the current request, which is used to get the user
    :param contact_id: Get the contact from the database
    :return: The edit
    :doc-author: Trelent
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    contact = Contacts.objects.get(pk=contact_id, user=request.user)
    form = ContactForm(request.POST or None, instance=contact)
    if form.is_valid():
        form.save()
        messages.success(request, "Contact was updated successfully !")
        return redirect(to='contacts:main')
    return render(request, 'contacts/edit.html', context={'form': form, 'contact': contact,
                                                          'avatar': avatar})


@login_required
def sort(request):
    """
    The sort function is used to sort the contacts by first name.
    It takes in a request and returns a render of the index page with the sorted contacts.

    :param request: Get the request object
    :return: The contacts sorted by firstname
    :doc-author: Trelent
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    contacts = Contacts.objects.filter(user=request.user).all().order_by(
        'firstname') if request.user.is_authenticated else []
    contacts_per_page = 15
    paginator = Paginator(contacts, contacts_per_page)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'contacts/index.html',
                  context={'contacts': contacts, 'user': request.user, 'page': page,
                           'avatar': avatar})


current_dir = os.path.dirname(os.path.abspath(__file__))


def save_csv_to_model(file_path):
    """
    The save_csv_to_model function takes a file path as an argument and saves the data in that CSV to the Contacts model.
    It does this by opening the file, reading it with csv.reader, skipping over the header row, and then iterating through each row of data in order to create a new instance of Contacts for each row.

    :param file_path: Specify the path to the file that we want to import
    :return: A list of the saved instances
    :doc-author: Trelent
    """
    with open(file_path, 'r') as csv_file:
        csv_reader = csv.reader(csv_file)
        next(csv_reader)  # Skip the header row
        for row in csv_reader:
            model_instance = Contacts()
            model_instance.firstname = row[0].strip()
            model_instance.lastname = row[1].strip()
            model_instance.phone = row[2].strip()
            model_instance.email = row[3].strip()
            model_instance.birthday = datetime.strptime(row[4].strip('\t'), '%Y-%m-%d').date()
            model_instance.save()


@login_required
def file_uploader(request):
    """
    The file_uploader function is responsible for uploading a CSV file to the server.
    It also saves the uploaded file in the database and then calls save_csv_to_model function, which saves all contacts from
    the CSV file into Contacts model.

    :param request: Get the request object
    :return: A render function that renders the index
    :doc-author: Trelent
    """

    if request.method == 'POST':
        try:
            csv_file = request.FILES.get('file')
            if not csv_file.name.endswith('.csv'):
                messages.warning(request, 'Invalid file format. Please upload a CSV file.')
                return redirect(to='contacts:main')
            csv_file_wrapper = TextIOWrapper(csv_file.file, encoding='utf-8')
            reader = csv.reader(csv_file_wrapper)
            next(reader)
            print(reader)

            for row in reader:
                try:
                    contacts = Contacts(
                        firstname=row[0],
                        lastname=row[1],
                        phone=row[2],
                        email=row[3],
                        birthday=row[4],
                        user=request.user,
                    )
                    contacts.save()
                except:
                    messages.warning(request, 'Wrong data in your CSV')
                    return redirect(to='contacts:main')

            messages.success(request, "File was uploaded successfully")
            return redirect(to='contacts:main')

contacts_web_app/contacts/templates/contacts/birthday.html
{% extends "users/base.html" %}

{% block content %}
{% if user.is_authenticated %}
<style>

td {font-weight:bold;}


</style>
<div class="text-center">
    <a href="{% url 'contacts:main' %}" class="btn btn-primary" style="width: 24%">Home</a>
    <a href="{% url 'contacts:contacts' %}" class="btn btn-primary" style="width: 24%">Add contact</a>
    <a href="{% url 'contacts:sort' %}" class="btn btn-primary" style="width: 24%">Sort by name</a>
    <a href="{% url 'contacts:birthday' %}" class="btn btn-primary" style="width: 24%">Birthday on this week</a>
</div>

<br>
{% if birthday_list %}
<h1><b>CONTACTS WHO HAS BIRTHDAY ON THIS WEEK</b></h1>
<br/>
<table class="table table-hover">
    <thead>
    <tr>
        <th style="background-color: #87CEEB;">Firstname</th>
        <th style="background-color: #87CEEB;">Lastname</th>
        <th style="background-color: #87CEEB;">Phone</th>
        <th style="background-color: #87CEEB;">Email</th>
        <th style="background-color: #87CEEB;">Birthday</th>
    </tr>
    </thead>
    <tbody>
    {% for contact in birthday_list %}
    <tr>
        <td>{{ contact.firstname }}</td>
        <td>{{ contact.lastname }}</td>
        <td><a href="tel:{{ contact.phone }}">{{ contact.phone }}</a></td>
        <td><a href="mailto:{{ contact.email }}">{{ contact.email }}</a></td>
        <td>{{ contact.birthday }}</td>
        <td><a href="{% url 'contacts:edit' contact.id %}" class="btn btn-outline-info btn-sm">Update</a></td>
        <td><a href="{% url 'contacts:delete_contact' contact.id %}" class="btn btn-outline-dark btn-sm">Delete</a>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h1>Nobody has birthday on this week</h1>
{% endif %}
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endblock %}

contacts_web_app/contacts/templates/contacts/contact.html
{% extends "users/base.html" %}

{% block content %}
{% if user.is_authenticated %}
<div class="text-center">
    <a href="{% url 'contacts:main' %}" class="btn btn-primary" style="width: 24%">Home</a>
    <a href="{% url 'contacts:contacts' %}" class="btn btn-primary" style="width: 24%">Add contact</a>
    <a href="{% url 'contacts:sort' %}" class="btn btn-primary" style="width: 24%">Sort by name</a>
    <a href="{% url 'contacts:birthday' %}" class="btn btn-primary" style="width: 24%">Birthday on this week</a>
</div>
<br>
<center>
    <h1><b>SAVE YOUR CONTACT</b></h1>
<form class="col-sm-6" method="POST" action="{% url 'contacts:contacts' %}">
    {% csrf_token %}
    <div style="padding: 10px">

        <div>
            <label>Enter the contact firstname:</label>
            {{form.firstname}}
            <span>{{ form.errors.firstname }}</span>
        </div>
        <br>
        <label>Enter the contact lastname:</label>
        {{form.lastname}}
        <span>{{ form.errors.lastname }}</span>
        <br>
        <label>Enter the contact phonenumber:</label>
        {{form.phone}}
        <span>{{ form.errors.phone }}</span>
        <br>
        <label>Enter the contact email:</label>
        {{form.email}}
        <span>{{ form.errors.email }}</span>
        <br>
        <label>Enter the contact birthay:</label>
        {{form.birthday}}
        <span>{{ form.errors.birthday }}</span>
    </div>
    <br>
    <center>
        <div class="grid">
            <button class="btn btn-outline-primary btn-block" type="submit">Submit</button>
            <button type="reset" class="btn btn-secondary btn">Reset</button>
        </div>
    </center>
</form>
</center>
<br><br><br><br>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}

contacts_web_app/contacts/templates/contacts/edit.html
{% extends "users/base.html" %}

{% block content %}
{% if user.is_authenticated %}
<div class="text-center">
    <a href="{% url 'contacts:main' %}" class="btn btn-primary" style="width: 24%">Home</a>
    <a href="{% url 'contacts:contacts' %}" class="btn btn-primary" style="width: 24%">Add contact</a>
    <a href="{% url 'contacts:sort' %}" class="btn btn-primary" style="width: 24%">Sort by name</a>
    <a href="{% url 'contacts:birthday' %}" class="btn btn-primary" style="width: 24%">Birthday on this week</a>
</div>
<br>
<center><h1><b>UPDATE YOUR CONTACT</b></h1>

<form class="col-sm-6" action="{% url 'contacts:edit' contact.id %}" method="post">
    {% csrf_token %}
        {{ form }}
    <br>
    <center>
    <div class="grid">
            <button class="btn btn-outline-primary btn-block" type="submit">Update</button>
            <a href="{% url 'contacts:main' %}" class="btn btn-secondary btn">Cancel</a>
    </div>

    </center>
</form>
</center>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}

{% endblock %}

contacts_web_app/contacts/templates/contacts/index.html
{% extends "users/base.html" %}

{% block content %}
{% if user.is_authenticated %}
<style>
th{
text-align: center;

}

td{
    color:#263B50;
    font-weight:bold;
}



</style>


<div class="text-center">
    <a href="{% url 'contacts:main' %}" class="btn btn-primary" style="width: 24%">Home</a>
    <a href="{% url 'contacts:contacts' %}" class="btn btn-primary" style="width: 24%">Add contact</a>
    <a href="{% url 'contacts:sort' %}" class="btn btn-primary" style="width: 24%">Sort by name</a>
    <a href="{% url 'contacts:birthday' %}" class="btn btn-primary" style="width: 24%">Birthday on this week</a>
</div>
<br/>
<h1 class="text-center"><b>CONTACTS</b></h1>

<br>
{% if form.errors %}
<span class="alert alert-danger" role="alert" id="error-message">{{form.non_field_errors}}</span>
{% endif %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert" id="message">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
<br>

<div class="form-box">
    <form action="{% url 'contacts:file_uploader' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="formFile" class="form-label mt-4">Upload CSV file:</label>
            <input class="form-control" type="file" id="formFile" name="file">
        </div>

        <br>
        <button type="submit" class="btn btn-primary">Upload CSV</button>
    </form>
</div>


<br>
<div class="d-flex justify-content-center align-items-center mx-auto">
    <form class="d-flex search-form" action="{% url 'contacts:search_contact'%}" method="POST">
        {% csrf_token %}
        <label class="text-center" style="font-weight: bold;"></label>
        <input class="form-control me-2" type="search" name="searched" placeholder="Search contact" aria-label="Search">
        <button class="btn btn-outline-primary btn-block" type="submit">Search</button>
    </form>
</div>

<br>
<br/>


{% if page %}

<table class="table table-hover">
    <thead>
    <tr>
        <th style="background-color: #87CEEB;">Firstname</th>
        <th style="background-color: #87CEEB;">Lastname</th>
        <th style="background-color: #87CEEB;">Phone</th>
        <th style="background-color: #87CEEB;">Email</th>
        <th style="background-color: #87CEEB;">Birthday</th>

    </tr>
    </thead>
    <tbody>
    {% for contact in page %}
    <tr class=active">
        <td>{{ contact.firstname }}</td>
        <td>{{ contact.lastname }}</td>
        <td><a href="tel:{{ contact.phone }}">{{ contact.phone }}</a></td>
        <td><a href="mailto:{{ contact.email }}">{{ contact.email }}</a></td>
        <td>{{ contact.birthday }}</td>
        <td><a href="{% url 'contacts:edit' contact.id %}" class="btn btn-outline-info btn-sm">Update</a></td>
        <td><a href="{% url 'contacts:delete_contact' contact.id %}" class="btn btn-outline-dark btn-sm">Delete</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h1>No contacts yet...</h1>
{% endif %}

<br>
<div>
    <ul class="pagination pagination-lg">
        <li class="page-item {% if not page.has_previous %}disabled{% endif %}">
            <a class="page-link" href="{% if page.has_previous %}?page=1{% else %}#{% endif %}">&laquo;</a>
        </li>
        {% for num in page.paginator.page_range %}
        {% if num == page.number %}
        <li class="page-item active">
            <a class="page-link" href="#">{{ num }}</a>
        </li>
        {% elif num > page.number|add:'-2' and num < page.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
        {% endfor %}
        <li class="page-item {% if not page.has_next %}disabled{% endif %}">
            <a class="page-link"
               href="{% if page.has_next %}?page={{ page.paginator.num_pages }}{% else %}#{% endif %}">&raquo;</a>
        </li>
    </ul>
</div>
<br>

<script>
    // Функція для автоматичного приховування повідомлення після певного часу
    function hideMessage() {
        var errorMessage = document.getElementById("error-message");
        var message = document.getElementById("message");

        if (errorMessage) {
            errorMessage.style.display = "none";
        }

        if (message) {
            message.style.display = "none";
        }
    }

    // Запуск функції приховування через 5 секунд
    setTimeout(hideMessage, 5000);
</script>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}

contacts_web_app/contacts/templates/contacts/search_contact.html
{% extends "users/base.html" %}

{% block content %}
{% if user.is_authenticated %}
<style>
    td {font-weight:bold;}

</style>


<div class="text-center">
    <a href="{% url 'contacts:main' %}" class="btn btn-primary" style="width: 24%">Home</a>
    <a href="{% url 'contacts:contacts' %}" class="btn btn-primary" style="width: 24%">Add contact</a>
    <a href="{% url 'contacts:sort' %}" class="btn btn-primary" style="width: 24%">Sort by name</a>
    <a href="{% url 'contacts:birthday' %}" class="btn btn-primary" style="width: 24%">Birthday on this week</a>
</div>

<br>

{% if contacts %}
<h1 style="text-align:center;"><b> CONTACTS YOU MAY SEARCH </b></h1>
<br/>
<table class="table table-hover">
    <thead>
    <tr>
        <th style="background-color: #87CEEB;">Firstname</th>
        <th style="background-color: #87CEEB;">Lastname</th>
        <th style="background-color: #87CEEB;">Phone</th>
        <th style="background-color: #87CEEB;">Email</th>
        <th style="background-color: #87CEEB;">Birthday</th>
    </tr>
    </thead>
    <tbody>
    {% for contact in contacts %}
    <tr>
        <td>{{ contact.firstname }}</td>
        <td>{{ contact.lastname }}</td>
        <td><a href="tel:{{ contact.phone }}">{{ contact.phone }}</a></td>
        <td><a href="mailto:{{ contact.email }}">{{ contact.email }}</a></td>
        <td>{{ contact.birthday }}</td>
        <td><a href="{% url 'contacts:edit' contact.id %}" class="btn btn-outline-info btn-sm">Update</a></td>
        <td><a href="{% url 'contacts:delete_contact' contact.id %}" class="btn btn-outline-dark btn-sm">Delete</a>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h1>Contacts with "{{ searched }}" not found</h1>
{% endif %}
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}