contacts_web_app/contacts_web_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('users.urls', namespace='default')),
    path('users/', include('users.urls')),
    path('notes/', include('notes.urls')),
    path('file_manager/', include('file_manager.urls')),
    path('contacts/', include('contacts.urls')),
    path('news/', include('news.urls')),
    path('adminconsole/', include('adminconsole.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts_web_app/file_manager/urls.py
from django.urls import path

from file_manager import views

app_name = "file_manager"

urlpatterns = [
    path('', views.main_mf, name='main_mf'),
    path('page/<int:page>/', views.main_mf, name='root_paginate'),
    path('picture/', views.upload_picture, name='upload_picture'),
    path('picture/delete/<int:picture_id>/', views.delete_picture, name='delete_picture'),
    path('picture/search_picture/', views.search_picture, name='search_picture'),
    path('document/', views.upload_document, name='upload_document'),
    path('document/delete/<int:document_id>/', views.delete_document, name='delete_document'),
    path('document/search_document/', views.search_document, name='search_document'),
    path('download_document/<path:document_url>/', views.download_document, name='download_document'),
    path('video/', views.upload_video, name='upload_video'),
    path('video/delete/<int:video_id>/', views.delete_video, name='delete_video'),
    path('video/search_video/', views.search_video, name='search_video'),
    path('audio/', views.upload_audio, name='upload_audio'),
    path('audio/delete/<int:audio_id>/', views.delete_audio, name='delete_audio'),
    path('audio/search_audio/', views.search_audio, name='search_audio'),
    path('archive/', views.upload_archive, name='upload_archive'),
    path('archive/delete/<int:archive_id>/', views.delete_archive, name='delete_archive'),
    path('archive/search_archive/', views.search_archive, name='search_archive'),
    path('download_image/<path:image_url>/', views.download_image, name='download_image'),
    path('download_archive/<path:archive_url>/', views.download_archive, name='download_archive'),
    path('bored/', views.main_mf, name='when_bored'),

]

contacts_web_app/news/urls.py
from django.urls import path

from .views import home, news_war, news_war_show_one, news_prosport, news_prosport_show_one, war_statistic, when_bored


app_name = "news"

urlpatterns = [
    path('', home, name='home'),
    path('news_war/', news_war, name='news_war'),
    path('news_war/<int:_id>', news_war_show_one, name='news_war_show_one'),
    path('news_prosport/', news_prosport, name='news_prosport'),
    path('news_prosport/<int:_id>', news_prosport_show_one, name='news_prosport_show_one'),
    path('war_statistic/', war_statistic, name='war_statistic'),
    path('bored/', when_bored, name='when_bored'),
]

contacts_web_app/file_manager/models.py
from django.contrib.auth.models import User
from django.db import models
from cloudinary.models import CloudinaryField
from django.utils import timezone


EXTENSIONS_IMG = ['jpeg', 'png', 'jpg', 'svg', 'gif']
EXTENSIONS_DOC = ['doc', 'docx', 'txt', 'pdf', 'xlsx', 'pptx', 'py', 'csv', 'css', 'html', 'js']
EXTENSIONS_VIDEO = ['avi', 'mp4', 'mov', 'mkv']
EXTENSIONS_MUSIC = ['mp3', 'ogg', 'wav', 'amr']
EXTENSIONS_ARCHIVES = ['zip', 'gz', 'tar', '7z', 'rar']


class Picture(models.Model):
    title = models.CharField(max_length=255, default='Unknown')
    image = CloudinaryField(resource_type='auto', allowed_formats=EXTENSIONS_IMG, folder='pictures')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)


class Document(models.Model):
    title = models.CharField(max_length=255, default='Unknown')
    document = CloudinaryField(resource_type='auto', allowed_formats=EXTENSIONS_DOC, folder='documents')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)


class Video(models.Model):
    title = models.CharField(max_length=255, default='Unknown')
    video = CloudinaryField(resource_type='auto', allowed_formats=EXTENSIONS_VIDEO, folder='video')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)


class Audio(models.Model):
    artist = models.CharField(max_length=50, default='Unknown', null=True)
    title = models.CharField(max_length=100, default='Unknown')
    audio = CloudinaryField(resource_type='auto', allowed_formats=EXTENSIONS_MUSIC, folder='audio')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)


class Archive(models.Model):
    title = models.CharField(max_length=100, default='Unknown')
    archive = CloudinaryField(resource_type='auto', allowed_formats=EXTENSIONS_ARCHIVES, folder='archives')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

contacts_web_app/file_manager/forms.py
from django.forms import ModelForm, TextInput, ClearableFileInput

from .models import Picture, Document, Video, Audio, Archive


class PictureForm(ModelForm):
    class Meta:
        model = Picture
        fields = ['title', 'image']
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'image': ClearableFileInput(attrs={'class': 'form-control-file'})}


class DocumentForm(ModelForm):
    class Meta:
        model = Document
        fields = ['title', 'document']
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'document': ClearableFileInput(attrs={'class': 'form-control-file'})}


class VideoForm(ModelForm):
    class Meta:
        model = Video
        fields = ['title', 'video']
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'video': ClearableFileInput(attrs={'class': 'form-control-file'}),
        }


class AudioForm(ModelForm):
    class Meta:
        model = Audio
        fields = ['artist', 'title', 'audio']
        widgets = {
            'artist': TextInput(attrs={'class': 'form-control'}),
            'title': TextInput(attrs={'class': 'form-control'}),
            'audio': ClearableFileInput(attrs={'class': 'form-control-file'}),
        }


class ArchiveForm(ModelForm):
    class Meta:
        model = Archive
        fields = ['title', 'archive']
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'archive': ClearableFileInput(attrs={'class': 'form-control-file'}),
        }

contacts_web_app/file_manager/views.py
import requests

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from cloudinary.exceptions import Error as CloudinaryError

from file_manager.models import Picture, Document, Video, Audio, Archive
from file_manager.forms import PictureForm, DocumentForm, VideoForm, AudioForm, ArchiveForm



@login_required
def main_mf(request):
    """
    The main_mf function is the main view for the file manager.
    It renders a template with an avatar object, which is used to display
    the user's profile picture in the top right corner of the page.

    :param request: Get the user's avatar from the database
    :return: A render with the context of avatar
    """
    url = "https://www.boredapi.com/api/activity/"
    response = requests.get(url).json()
    context = {
        'bored': response,
    }
    return render(request, 'file_manager/index.html', context=context)


@login_required
def upload_picture(request):
    """
    The upload_picture function is responsible for uploading a picture to the cloudinary server.
    It also displays all of the pictures that have been uploaded by the user.

    :param request: Get the request object
    :return: The render function
    """
    exp_message = "File not valid, you can upload the following types of files: 'jpeg', 'png', 'jpg', 'svg', 'gif'"
    user_id = request.user.id
    cloud_images = Picture.objects.filter(user_id=user_id)
    page_obj = pagination(request, cloud_images)
    image_form = PictureForm()

    if request.method == 'POST':
        form = PictureForm(request.POST, request.FILES)
        try:
            if form.is_valid():
                pic = form.save(commit=False)
                pic.user = request.user
                picture_file = form.cleaned_data['image']
                max_file_size = 1024 * 1024
                if picture_file.size > max_file_size:
                    messages.warning(request, "The uploaded image file is too large. Must be to 1Mb")
                    return redirect(request.META['HTTP_REFERER'])
                pic.save()
                return redirect(request.META['HTTP_REFERER'])
        except CloudinaryError:
            messages.warning(request, exp_message)
            return redirect(request.META['HTTP_REFERER'])

    context = {
        'cloud_images': page_obj,
        'image_form': image_form,
    }
    return render(request, 'file_manager/upload_picture.html', context=context)


@login_required
def download_image(request, image_url):
    """
    The download_image function takes a request and an image_url as arguments.
    It then makes a GET request to the image_url, gets the content-type from the response headers,
    and saves it in a variable called content_type. It also splits up the URL into its component parts using split(),
    and saves only the last part of that list (the filename) in another variable called filename.
    Then it creates an HttpResponse object with response's content and our previously saved content type,
    sets Content-Disposition to attachment; filename=&quot;{filename}&quot;, and returns this new HttpResponse object.

    :param request: Get the request object
    :param image_url: Pass the image url to the function
    :return: An image file with the specified url
    """
    response = requests.get(image_url)
    content_type = response.headers.get('content-type')
    filename = image_url.split('/')[-1]  # Отримати назву файлу з URL
    response = HttpResponse(response.content, content_type=content_type)
    response['Content-Disposition'] = f'attachment; filename="{filename}"'

    return response


@login_required
def delete_picture(request, picture_id):
    """
    The delete_picture function takes a request and picture_id as arguments.
    It gets the picture with the given id, which is owned by the user making
    the request, and deletes it. It then displays a success message to let them know
    that their picture was deleted successfully.

    :param request: Get the current user
    :param picture_id: Get the picture that we want to delete
    :return: The redirect function which returns a httpresponseredirect object
    """
    picture = Picture.objects.get(id=picture_id, user=request.user)
    picture.delete()
    messages.success(request, "Picture deleted successfully.")
    return redirect(request.META['HTTP_REFERER'])


def search_picture(request):
    """
    The search_picture function is used to search for a picture in the database.
        The function takes a request as an argument and returns the result of searching
        for pictures by title.

    :param request: Get the request object
    :return: The search_picture
    """
    query = request.GET.get("q")
    if query:
        files = Picture.objects.filter(Q(title__icontains=query))
        files_search = pagination(request, files)
        context = {
            "query": query,
            "cloud_images": files_search,
        }
        return render(request, "file_manager/search_picture.html", context=context)
    messages.success(request, "Enter your request.")
    return redirect(request.META['HTTP_REFERER'])


@login_required
def upload_video(request):
    """
    The upload_video function is responsible for uploading a video to the cloudinary server.
        It also displays all videos uploaded by the user on the same page.

    :param request: Get the request object
    :return: A render of the upload_video
    """
    exp_message = "File not valid, you can upload the following types of files: 'avi', 'mp4', 'mov', 'mkv'"
    user_id = request.user.id
    cloud_video = Video.objects.filter(user_id=user_id)
    page_obj = pagination(request, cloud_video)
    video_form = VideoForm()
    if request.method == 'POST':
        form = VideoForm(request.POST, request.FILES)
        if form.is_valid():
            video_file = form.cleaned_data['video']
            max_size = 10 * 1024 * 1024

            if video_file.size <= max_size:
                try:
                    video = form.save(commit=False)
                    video.user = request.user
                    video.save()
                    return redirect(request.META['HTTP_REFERER'])
                except CloudinaryError:
                    messages.warning(request, exp_message)
                    return redirect(request.META['HTTP_REFERER'])
            else:
                messages.warning(request, "The uploaded video file is too large. Must be to 10Mb")
                return redirect(request.META['HTTP_REFERER'])
    context = {
        'cloud_video': page_obj,
        'video_form': video_form,
    }
    return render(request, 'file_manager/upload_video.html', context=context)


@login_required
def delete_video(request, video_id):
    """
    The delete_video function deletes a video from the database.
        Args:
            request (HttpRequest): The request object sent by the user.
            video_id (int): The id of the video to be deleted.

    :param request: Get the current user
    :param video_id: Identify the video that is to be deleted
    :return: The http_referer
    """
    video = Video.objects.get(id=video_id, user=request.user)
    video.delete()
    messages.success(request, "Video deleted successfully.")
    return redirect(request.META['HTTP_REFERER'])


def search_video(request):
    """
    The search_video function is used to search for videos in the database.
        The function takes a request object as an argument and returns a rendered template with the results of the query.
        If there are no results, it redirects back to where it came from.

    :param request: Get the request object from the view
    :return: The following error:
    """
    query = request.GET.get("q")
    if query:
        files = Video.objects.filter(Q(title__icontains=query))
        files_search = pagination(request, files)
        context = {
            "query": query,
            "cloud_video": files_search,
        }
        return render(request, "file_manager/search_video.html", context=context)
    messages.success(request, "Enter your request.")
    return redirect(request.META['HTTP_REFERER'])


@login_required
def upload_document(request):
    """
    The upload_document function is responsible for uploading documents to the cloud.
        It also displays all uploaded documents on the page.

    :param request: Get the request object
    :return: A redirect to the same page
    """
    exp_message = "File not valid, you can upload the following types of files: 'doc', 'docx', 'txt', 'pdf', 'xlsx', " \
                  "'pptx', 'py', 'csv', 'css', 'html', 'js'"
    user_id = request.user.id
    cloud_document = Document.objects.filter(user_id=user_id)
    page_obj = pagination(request, cloud_document)
    document_form = DocumentForm()
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        try:
            if form.is_valid():
                doc = form.save(commit=False)
                doc.user = request.user
                max_file_size = 1024 * 1024
                doc_file = form.cleaned_data['document']
                if doc_file.size > max_file_size:
                    messages.warning(request, "The uploaded document file is too large. Must be to 1Mb")
                    return redirect(request.META['HTTP_REFERER'])
                doc.save()
                return redirect(request.META['HTTP_REFERER'])
        except CloudinaryError:
            messages.warning(request, exp_message)
            return redirect(request.META['HTTP_REFERER'])

    context = {
        'cloud_document': page_obj,
        'document_form': document_form,

    }
    return render(request, 'file_manager/upload_document.html', context=context)


@login_required

contacts_web_app/file_manager/templates/file_manager/search_archive.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}
<div class="text-center">
    <a href="{% url 'file_manager:upload_picture' %}" class="btn btn-primary" style="width: 19%">Pictures</a>
    <a href="{% url 'file_manager:upload_video' %}" class="btn btn-primary" style="width: 19%">Video</a>
    <a href="{% url 'file_manager:upload_audio' %}" class="btn btn-primary" style="width: 19%">Audio</a>
    <a href="{% url 'file_manager:upload_document' %}" class="btn btn-primary" style="width: 19%">Documents</a>
    <a href="{% url 'file_manager:upload_archive' %}" class="btn btn-primary" style="width: 19%">Archive</a>
</div>
<br>
<h1>Search results: {{ query }}</h1>
<br>
<h2 class="text-center">Cloud Archive</h2>
<br>
<div class="d-flex justify-content-center align-items-center mx-auto">
    <form class="d-flex search-form" action="{% url 'file_manager:search_archive' %}" method="get">
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary" type="submit">Search</button>
    </form>
</div>
<br>
{% if form.errors %}
<span class="alert alert-danger" role="alert" id="error-message">{{form.non_field_errors}}</span>
{% endif %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert" id="message">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
<br>
{% csrf_token %}
{% if not cloud_archive %}
<div>Not found "{{query}}"</div>
{% endif %}
<br>
<div>
    <ul class="archive-list">
        {% for archive in cloud_archive %}
        <li class="archive-item">
            <div class="archive-details">
                <div class="archive-title">{{ archive.title|truncatechars:50 }}</div>
            </div>
            <div class="archive-actions">
                <a href="{% url 'file_manager:download_archive' archive.archive.url %}"
                   class="badge rounded-pill bg-light" style="text-decoration: none;">Download</a>
                <button class="badge rounded-pill bg-dark delete-archive-button" data-archive-id="{{ archive.id }}">
                    Delete
                </button>
            </div>
        </li>
        {% empty %}
        <li>
            <h2 class="text-center">No available archive.</h2>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmDeleteModalLabel">Confirm Archive Deletion</h5>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this Archive?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark" id="confirmDeleteButton">Delete</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal" id="cancelDeleteButton">Cancel
                </button>

            </div>
        </div>
    </div>
</div>
<br>
<div>
    <ul class="pagination pagination-lg">
        <li class="page-item {% if not cloud_archive.has_previous %}disabled{% endif %}">
            <a class="page-link" href="{% if cloud_archive.has_previous %}?page=1{% else %}#{% endif %}">&laquo;</a>
        </li>
        {% for num in cloud_archive.paginator.page_range %}
        {% if num == cloud_archive.number %}
        <li class="page-item active">
            <a class="page-link" href="#">{{ num }}</a>
        </li>
        {% elif num > cloud_archive.number|add:'-2' and num < cloud_archive.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
        {% endfor %}
        <li class="page-item {% if not cloud_archive.has_next %}disabled{% endif %}">
            <a class="page-link"
               href="{% if cloud_archive.has_next %}?page={{ cloud_archive.paginator.num_pages }}{% else %}#{% endif %}">&raquo;</a>
        </li>
    </ul>
</div>
<br>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    var deleteArchiveId;

    $(".delete-archive-button").on("click", function() {
        deleteArchiveId = $(this).data("archive-id");
        $("#confirmDeleteModal").modal("show");
    });

    $("#confirmDeleteButton").on("click", function() {
        deleteArchive(deleteArchiveId);
    });

    function deleteArchive(archiveId) {
        var deleteArchiveUrl = "{% url 'file_manager:delete_archive' archive_id=0 %}".replace("0", archiveId);
        window.location.href = deleteArchiveUrl;
    }

    $("#cancelDeleteButton").on("click", function() {
        $("#confirmDeleteModal").modal("hide");
    });
});

function downloadArchive(url, filename) {
    var anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = filename;
    anchor.style.display = 'none';
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
}
</script>
<script>
    // Функція для автоматичного приховування повідомлення після певного часу
    function hideMessage() {
        var errorMessage = document.getElementById("error-message");
        var message = document.getElementById("message");

        if (errorMessage) {
            errorMessage.style.display = "none";
        }

        if (message) {
            message.style.display = "none";
        }
    }

    // Запуск функції приховування через 5 секунд
    setTimeout(hideMessage, 5000);
</script>
<style>
.archive-item {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 10px;
}

.archive-title {
    flex-grow: 1;
}

.archive-actions {
    margin-left: 10px;
}
</style>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
        </div>
{% endif %}
{% endblock %}

contacts_web_app/file_manager/templates/file_manager/search_document.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}
<div class="text-center">
    <a href="{% url 'file_manager:upload_picture' %}" class="btn btn-primary" style="width: 19%">Pictures</a>
    <a href="{% url 'file_manager:upload_video' %}" class="btn btn-primary" style="width: 19%">Video</a>
    <a href="{% url 'file_manager:upload_audio' %}" class="btn btn-primary" style="width: 19%">Audio</a>
    <a href="{% url 'file_manager:upload_document' %}" class="btn btn-primary" style="width: 19%">Documents</a>
    <a href="{% url 'file_manager:upload_archive' %}" class="btn btn-primary" style="width: 19%">Archive</a>
</div>
<br>
<h1>Search results: {{ query }}</h1>
<br>
<h2 class="text-center">Cloud Document</h2>
<br>
<div class="d-flex justify-content-center align-items-center mx-auto">
    <form class="d-flex search-form" action="{% url 'file_manager:search_document' %}" method="get">
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary" type="submit">Search</button>
    </form>
</div>
<br>
{% if form.errors %}
<span class="alert alert-danger" role="alert" id="error-message">{{form.non_field_errors}}</span>
{% endif %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert" id="message">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
<br>
{% csrf_token %}
{% if not cloud_document %}
<div>Not found "{{query}}"</div>
{% endif %}
<br>
<div>
    <ul class="document-list">
        {% for document in cloud_document %}
        <li class="document-item">
            <div class="document-details">
                <div class="document-title">{{ document.title|truncatechars:50 }}</div>
            </div>
            <div class="document-actions">
                <a href="{% url 'file_manager:download_document' document.document.url %}"
                   class="badge rounded-pill bg-light" style="text-decoration: none;">Download</a>
                <button class="badge rounded-pill bg-dark delete-document-button" data-document-id="{{ document.id }}">
                    Delete
                </button>
            </div>
        </li>
        {% empty %}
        <li>
            <h2 class="text-center">No available documents.</h2>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmDeleteModalLabel">Confirm Document Deletion</h5>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this Document?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark" id="confirmDeleteButton">Delete</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal" id="cancelDeleteButton">Cancel
                </button>

            </div>
        </div>
    </div>
</div>
<br>
<div>
    <ul class="pagination pagination-lg">
        <li class="page-item {% if not cloud_document.has_previous %}disabled{% endif %}">
            <a class="page-link" href="{% if cloud_document.has_previous %}?page=1{% else %}#{% endif %}">&laquo;</a>
        </li>
        {% for num in cloud_document.paginator.page_range %}
        {% if num == cloud_document.number %}
        <li class="page-item active">
            <a class="page-link" href="#">{{ num }}</a>
        </li>
        {% elif num > cloud_document.number|add:'-2' and num < cloud_document.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
        {% endfor %}
        <li class="page-item {% if not cloud_document.has_next %}disabled{% endif %}">
            <a class="page-link"
               href="{% if cloud_document.has_next %}?page={{ cloud_document.paginator.num_pages }}{% else %}#{% endif %}">&raquo;</a>
        </li>
    </ul>
</div>
<br>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    var deleteDocumentId;

    $(".delete-document-button").on("click", function() {
        deleteDocumentId = $(this).data("document-id");
        $("#confirmDeleteModal").modal("show");
    });

    $("#confirmDeleteButton").on("click", function() {
        deleteDocument(deleteDocumentId);
    });

    function deleteDocument(documentId) {
        var deleteDocumentUrl = "{% url 'file_manager:delete_document' document_id=0 %}".replace("0", documentId);
        window.location.href = deleteDocumentUrl;
    }

    $("#cancelDeleteButton").on("click", function() {
        $("#confirmDeleteModal").modal("hide");
    });
});

function downloadArchive(url, filename) {
    var anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = filename;
    anchor.style.display = 'none';
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
}
</script>
<script>
    // Функція для автоматичного приховування повідомлення після певного часу
    function hideMessage() {
        var errorMessage = document.getElementById("error-message");
        var message = document.getElementById("message");

        if (errorMessage) {
            errorMessage.style.display = "none";
        }

        if (message) {
            message.style.display = "none";
        }
    }

    // Запуск функції приховування через 5 секунд
    setTimeout(hideMessage, 5000);
</script>
<style>
.document-item {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 10px;
}

.document-title {
    flex-grow: 1;
}

.document-actions {
    margin-left: 10px;
}
</style>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
        </div>
{% endif %}
{% endblock %}