contacts_web_app/contacts_web_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('users.urls', namespace='default')),
    path('users/', include('users.urls')),
    path('notes/', include('notes.urls')),
    path('file_manager/', include('file_manager.urls')),
    path('contacts/', include('contacts.urls')),
    path('news/', include('news.urls')),
    path('adminconsole/', include('adminconsole.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts_web_app/news/urls.py
from django.urls import path

from .views import home, news_war, news_war_show_one, news_prosport, news_prosport_show_one, war_statistic, when_bored


app_name = "news"

urlpatterns = [
    path('', home, name='home'),
    path('news_war/', news_war, name='news_war'),
    path('news_war/<int:_id>', news_war_show_one, name='news_war_show_one'),
    path('news_prosport/', news_prosport, name='news_prosport'),
    path('news_prosport/<int:_id>', news_prosport_show_one, name='news_prosport_show_one'),
    path('war_statistic/', war_statistic, name='war_statistic'),
    path('bored/', when_bored, name='when_bored'),
]

contacts_web_app/notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'

urlpatterns = [
    path('', views.main, name='main'),
    path('note/', views.note, name='note'),
    path('tag/', views.tag, name='tag'),
    path('detail/<int:note_id>', views.detail, name='detail'),
    path('done/<int:note_id>', views.set_done, name='set_done'),
    path('delete/<int:note_id>', views.delete_note, name='delete'),
    path('edit/<int:note_id>', views.edit_note, name='edit_note'),
    path('search/', views.search, name='search'),
    path('sort/', views.sort, name='sort'),
]

contacts_web_app/notes/models.py
from django.db import models
from django.contrib.auth.models import User


class Tag(models.Model):
    name = models.CharField(max_length=25, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='tag of username')
        ]

    def __str__(self):
        return f'{self.name}'


class Note(models.Model):
    name = models.CharField(max_length=50, null=False)
    description = models.CharField(max_length=250, null=False)
    done = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f'{self.name}'

contacts_web_app/notes/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Note, Tag


class TagForm(ModelForm):

    name = CharField(min_length=1, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']
        

class NoteForm(ModelForm):

    name = CharField(min_length=1, max_length=50, required=True, widget=TextInput())
    description = CharField(min_length=1, max_length=250, required=True, widget=TextInput())

    class Meta:
        model = Note
        fields = ['name', 'description']
        exclude = ['tags']

contacts_web_app/notes/views.py
from datetime import date
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import NoteForm, TagForm
from .models import Tag, Note

from users.models import Avatar


def main(request):
    """
    The main function is the view for the main page of our site.
    It displays all notes and tags that belong to a user if they are logged in, or an empty list otherwise.
    It also paginates notes so that only 9 are displayed per page.
    
    :param request: Get the current request object
    :return: A render function
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    notes = Note.objects.filter(user=request.user).all() if request.user.is_authenticated else []
    tags = Tag.objects.filter(user=request.user).all() if request.user.is_authenticated else []
    # paginator = Paginator(notes, 9)
    # page_number = request.GET.get('page', 1)
    # try:
    #     pages = paginator.page(page_number)
    # except PageNotAnInteger:
    #     pages = paginator.page(1)
    # except EmptyPage:
    #     pages = paginator.page(paginator.num_pages)
    pages = pagination(request, notes)
    return render(request, 'notes/index.html', context={'notes': pages, 'tags': tags, 'avatar': avatar})


@login_required
def tag(request):
    """
    The tag function is used to create a new tag.
        It takes in the request and returns a rendered template of the form.
        If it's a POST request, then it will save the data from that form into our database.
    
    :param request: Get the current request object
    :return: A redirect to the main page
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            tag.save()
            return redirect(to='notes:main')
        else:
            return render(request, 'notes/tag.html', {'form': form, 'avatar': avatar})

    return render(request, 'notes/tag.html', {'form': TagForm(), 'avatar': avatar})


@login_required
def note(request):
    """
    The note function is responsible for creating a new note.
    It first gets all the tags that belong to the user and passes them to the template.
    Then it checks if there was a POST request, which means that someone submitted data through our form.
    If so, we create an instance of NoteForm with this data and check if it's valid (if all fields are filled
    correctly). If not, we render our template again but this time with errors in form fields (they will be
    highlighted). Otherwise we save our new note without committing changes yet because we need to add some tags first.
    Then we get all chosen tags from request body and
    
    :param request: Get the data from the form
    :return: The note
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    tags = Tag.objects.filter(user=request.user).all()

    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.user = request.user
            new_note.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'), user=request.user)
            for tag in choice_tags.iterator():
                new_note.tags.add(tag)

            return redirect(to='notes:main')
        else:
            return render(request, 'notes/note.html', {'tags': tags, 'form': form})

    return render(request, 'notes/note.html', {'tags': tags, 'form': NoteForm(), 'avatar': avatar})


@login_required
def detail(request, note_id):
    """
    The detail function is used to display a single note.
    It takes the request and the note_id as parameters, and returns a rendered template with the requested note.
    If no such note exists, it raises an Http404 exception.
    
    :param request: Get the current user
    :param note_id: Retrieve the note from the database
    :return: A httpresponseredirect object
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    note = get_object_or_404(Note, pk=note_id, user=request.user)
    return render(request, 'notes/detail.html', {'note': note, 'avatar': avatar})


@login_required
def set_done(request, note_id):
    """
    The set_done function takes a request and note_id as arguments.
    It then filters the Note objects by the primary key of note_id, 
    and updates the done field to True. It then redirects to 'notes:main'. 
    
    :param request: Get the user from the request object
    :param note_id: Find the note that we want to mark as done
    :return: A redirect to the main page
    """
    Note.objects.filter(pk=note_id, user=request.user).update(done=True)
    return redirect(to='notes:main')


@login_required
def delete_note(request, note_id):
    """
    The delete_note function takes in a request and note_id,
        then deletes the Note object with the given id.
        It redirects to 'notes:main' after deleting.
    
    :param request: Get the user information from the request object
    :param note_id: Find the note to delete
    :return: A redirect to the main view
    """
    Note.objects.get(pk=note_id, user=request.user).delete()
    return redirect(to='notes:main')


@login_required
def edit_note(request, note_id):
    """
    The edit_note function is responsible for editing a note.
    It takes the request and note_id as parameters, gets the Note object with that id or returns 404 if it doesn't exist,
    gets all tags of this user and checks if the request method is POST. If so, it creates a form from NoteForm class with
    the data from POST request and instance of edited note (note). If form is valid then we create an edited_note variable 
    with data from form but without saving to database yet. Then we set its user attribute to current logged in user 
    (request.user) and save it to database using .
    
    :param request: Get the request object
    :param note_id: Get the note object from the database
    :return: The render function
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    note = get_object_or_404(Note, pk=note_id, user=request.user)
    tags = Tag.objects.filter(user=request.user).all()

    if request.method == 'POST':
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            edited_note = form.save(commit=False)
            edited_note.user = request.user
            edited_note.save()
            edited_note.tags.clear()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'), user=request.user)
            for tag in choice_tags.iterator():
                edited_note.tags.add(tag)

            return redirect(to='notes:main')
        else:
            return render(request, 'notes/edit_note.html', {'note': note, 'tags': tags, 'form': form,
                                                            'avatar': avatar})

    form = NoteForm(instance=note)
    return render(request, 'notes/edit_note.html', {'note': note, 'tags': tags, 'form': form,
                                                    'avatar': avatar})


@login_required
def search(request):
    """
    The search function takes a request and returns the search results.
    If there is no query in the request, it redirects to main.
    Otherwise, it filters notes by name or description and renders them.
    
    :param request: Pass the request object to the view
    :return: A list of notes that match the query
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    if 'query' in request.GET:
        query = request.GET['query']
        notes = Note.objects.filter(
            Q(name__icontains=query) | Q(description__icontains=query),
            user=request.user
        )
        search_notes = pagination(request, notes)
        return render(request, 'notes/search_results.html', {'notes': search_notes,
                                                             'avatar': avatar})
    else:
        return redirect(to='notes:main')


@login_required
def sort(request):
    """
    The sort function takes in a request object and returns the search_results.html template with notes that have been
    filtered by tags selected by the user.
    
    :param request: Get the request object
    :return: A list of notes that have the selected tags
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    if request.method == 'GET':
        selected_tags = request.GET.getlist('selected_tags')
        notes = Note.objects.filter(tags__name__in=selected_tags, user=request.user).distinct()
        return render(request, 'notes/search_results.html', {'notes': notes, 'selected_tags': selected_tags,
                                                             'avatar': avatar})
    else:
        return redirect(to='notes:main')


def pagination(request, files):

    """
    The pagination function takes in a request and a list of files.
    It then creates a paginator object with the number of items per page set to 9,
    and the list of files as its argument. It then gets the current page number from
    the request, and returns an object containing that page's information.

    :param request: Get the current page number
    :param files: Pass the files to be paginated
    :return: A page object
    :doc-author: Trelent
    """
    per_page = 9
    paginator = Paginator(list(files), per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj

contacts_web_app/notes/templates/notes/detail.html
{% extends "users/base.html" %}
{% load extract_tags %}

{% block content %}
{% if user.is_authenticated %}
<div class="form-box shadow-lg bg-body-tertiary rounded-5">
    <h1 class="fw-bold">{{note.name}}</h1>
    <p>Description: <b>{{note.description}}</b></p>
    <p>Time of creation: {{note.created}}</p>
    {% if note.done %}
    <p>Status:
        <b class="text-primary">Completed</b>
    </p>
    {% else %}
    <p>Status: <b class="text-dark">In progress</b></p>
    {% endif %}
    <p >Tags: <small class="badge rounded-pill bg-primary text-wrap">
        {{ note.tags|tags }}
    </small></p>
</div>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}

contacts_web_app/notes/templates/notes/edit_note.html
{% extends "users/base.html" %}

{% block content %}
{% if user.is_authenticated %}
<div class="form-box shadow-lg bg-body-tertiary rounded-5">
    <h1 class="text-center"><b>Edit Note</b></h1>

    <form method="POST" action="{% url 'notes:edit_note' note.id %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="name" class="form-label">Note name:</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ note.name }}" required>
            <span class="text-danger">{{ form.errors.name }}</span>
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Note description:</label>
            <textarea class="form-control" id="description" name="description" rows="4" required>{{ note.description }}</textarea>
            <span class="text-danger">{{ form.errors.description }}</span>
        </div>
        <div class="mb-3">
            <label for="tags" class="form-label">Select tags:</label>
            <select name="tags" id="tags" class="form-control" multiple required>
                {% for tag in tags %}
                <option value="{{tag.name}}" {% if tag in note.tags.all %}selected{% endif %}>{{tag.name}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="grid">
            <button type="submit" class="btn btn-outline-primary">Update</button>
            <button type="reset" class="btn btn-outline-secondary">Reset</button>
        </div>
    </form>
</div>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}

contacts_web_app/notes/templates/notes/index.html
{% extends 'users/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<h1 class="text-center"><b>NOTES</b></h1>
<div class="row">
    <div class="col-md-12">
        <div class="btn-group-horizontal" role="group" aria-label="Button Group">
            <a href="{% url 'notes:note' %}" class="btn btn-outline-primary btn-block">Add Note</a>
            <a href="{% url 'notes:tag' %}" class="btn btn-secondary btn-block">Add Tag</a>
        </div>
    </div>
    <div class="col-md-12">
        <form method="GET" action="{% url 'notes:search' %}" class="mb-4 border p-3">
            <div class="input-group">
                <input type="text" name="query" class="form-control p-3" placeholder="Search notes..." required>
                <button type="submit" class="btn btn-outline-primary">Search</button>
            </div>
        </form>

        <form method="GET" action="{% url 'notes:sort' %}" class="mb-4 border p-3">
            {% csrf_token %}
            <div class="input-group">
                <label class="input-group-text">Select tags:</label>
                <select class="form-select" aria-label="Default select example" name="selected_tags">
                    <option selected></option>
                    {% for tag in tags.all %}
                    <option value="{{ tag.name }}">{{ tag.name }}</option>
                    {% endfor %}
                </select>

                <button type="submit" class="btn btn-outline-primary">Filter</button>
            </div>
        </form>

        <div class="row">
            {% for note in notes %}
            <div class="col-4">
                <div class="card mb-3">
                    <div class="card-body shadow bg-body-tertiary rounded-5">
                        {% if not note.done %}
                        <h5 class="card-title fw-bold">{{ note.name }}</h5>
                        <p class="card-text">{{ note.description }}</p>
                        <a href="{% url 'notes:set_done' note.id %}" class="btn btn-outline-primary btn-sm">Mark
                            Done</a>
                        {% else %}
                        <h5 class="card-title fw-bold">{{ note.name }} <i
                                class="bi bi-check-circle-fill text-primary"></i></h5>
                        <p class="card-text">{{ note.description }}</p>

                        {% endif %}
                        <div class="btn-group" role="group" aria-label="Note Actions">
                            <a href="{% url 'notes:detail' note.id %}"
                               class="btn btn-outline-secondary btn-sm">Details</a>
                            <a href="{% url 'notes:edit_note' note.id %}" class="btn btn-outline-info btn-sm">Edit</a>
                            <a href="{% url 'notes:delete' note.id %}" class="btn btn-outline-dark btn-sm">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>No notes found.</p>
            {% endfor %}
        </div>
    </div>
</div>
<br>
<div>
    <ul class="pagination pagination-lg">
        <li class="page-item {% if not notes.has_previous %}disabled{% endif %}">
            <a class="page-link" href="{% if notes.has_previous %}?page=1{% else %}#{% endif %}">&laquo;</a>
        </li>
        {% for num in notes.paginator.page_range %}
        {% if num == notes.number %}
        <li class="page-item active">
            <a class="page-link" href="#">{{ num }}</a>
        </li>
        {% elif num > notes.number|add:'-2' and num < notes.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
        {% endfor %}
        <li class="page-item {% if not notes.has_next %}disabled{% endif %}">
            <a class="page-link"
               href="{% if notes.has_next %}?page={{ notes.paginator.num_pages }}{% else %}#{% endif %}">&raquo;</a>
        </li>
    </ul>
</div>
<br>
<!--{% include "notes/pagination.html" with page=notes %}-->
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}

contacts_web_app/notes/templates/notes/note.html
{% extends "users/base.html" %}

{% block content %}
{% if user.is_authenticated %}
<div class="form-box shadow-lg bg-body-tertiary rounded-5">
    <h1 class="text-center"><b>Create Note</b></h1>

    <form method="POST" action="{% url 'notes:note' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="name" class="form-label">Note name:</label>
            <input type="text" class="form-control" id="name" name="name" required>
            <span class="text-danger">{{ form.errors.name }}</span>
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Note description:</label>
            <textarea class="form-control" id="description" name="description" rows="4" required></textarea>
            <span class="text-danger">{{ form.errors.description }}</span>
        </div>
        <div class="mb-3">
            <label for="tags" class="form-label">Select tags:</label>
            <select name="tags" id="tags" class="form-control" multiple required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="grid">
            <button type="submit" class="btn btn-outline-primary">Submit</button>
            <button type="reset" class="btn btn-outline-secondary">Reset</button>
        </div>
    </form>
</div>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}

contacts_web_app/notes/templates/notes/pagination.html
<div class="container">
    <div class="row justify-content-center">
        <div class="col-auto">
            <div class="pagination badge rounded-pill text-bg-secondary d-flex justify-content-center text-center">
                <span class="step-links">
                    {% if page.has_previous %}
                        <a href="?page={{ page.previous_page_number }}"><span class="badge rounded-pill text-bg-primary">Previous</span></a>
                    {% endif %}
                    <span class="current">
                        Page {{ page.number }} of {{ page.paginator.num_pages }}
                    </span>
                    {% if page.has_next %}
                        <a href="?page={{ page.next_page_number }}"><span class="badge rounded-pill text-bg-primary">Next</span></a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>

contacts_web_app/notes/templates/notes/search_results.html
{% extends "users/base.html" %}

{% block content %}
{% if user.is_authenticated %}
<div class="row rounded-5">
    <h1 class="text-center"><b>Search Results</b></h1>


    {% if notes %}
    {% for note in notes %}
    <div class="col-4">
        <div class="card mb-3">
            <div class="card-body shadow bg-body-tertiary rounded-3">
                {% if not note.done %}
                <h5 class="card-title fw-bold">{{ note.name }}</h5>
                <p class="card-text">{{ note.description }}</p>
                <a href="{% url 'notes:set_done' note.id %}" class="btn btn-outline-primary btn-sm">Mark Done</a>
                {% else %}
                <h5 class="card-title fw-bold">{{ note.name }} <i class="bi bi-check-circle-fill text-primary"></i></h5>
                <p class="card-text">{{ note.description }}</p>
                {% endif %}
                <div class="btn-group" role="group" aria-label="Note Actions">
                    <a href="{% url 'notes:detail' note.id %}" class="btn btn-outline-secondary btn-sm">Details</a>
                    <a href="{% url 'notes:edit_note' note.id %}" class="btn btn-outline-info btn-sm">Edit</a>
                    <a href="{% url 'notes:delete' note.id %}" class="btn btn-outline-dark btn-sm">Delete</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p class="text-center">No notes found.</p>
    {% endif %}
</div>
<br>
<div>
    <ul class="pagination pagination-lg">
        <li class="page-item {% if not notes.has_previous %}disabled{% endif %}">
            <a class="page-link" href="{% if notes.has_previous %}?page=1{% else %}#{% endif %}">&laquo;</a>
        </li>
        {% for num in notes.paginator.page_range %}
        {% if num == notes.number %}
        <li class="page-item active">
            <a class="page-link" href="#">{{ num }}</a>
        </li>
        {% elif num > notes.number|add:'-2' and num < notes.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
        {% endfor %}
        <li class="page-item {% if not notes.has_next %}disabled{% endif %}">
            <a class="page-link"
               href="{% if notes.has_next %}?page={{ notes.paginator.num_pages }}{% else %}#{% endif %}">&raquo;</a>
        </li>
    </ul>
</div>
<br>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}

contacts_web_app/notes/templates/notes/tag.html
{% extends "users/base.html" %}

{% block content %}
{% if user.is_authenticated %}
<div class="form-box shadow-lg bg-body-tertiary rounded-5">
    <h1 class="text-center"><b>Create Tag</b></h1>

    <form method="POST" action="{% url 'notes:tag' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="name" class="form-label">Enter the tag name:</label>
            <input type="text" class="form-control" id="name" name="name" required>
            <span class="text-danger">{{ form.errors.name }}</span>
        </div>
        <div class="grid">
            <button type="submit" class="btn btn-outline-primary">Submit</button>
            <button type="reset" class="btn btn-outline-secondary">Reset</button>
        </div>
    </form>
</div>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}