contacts_web_app/contacts_web_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('users.urls', namespace='default')),
    path('users/', include('users.urls')),
    path('notes/', include('notes.urls')),
    path('file_manager/', include('file_manager.urls')),
    path('contacts/', include('contacts.urls')),
    path('news/', include('news.urls')),
    path('adminconsole/', include('adminconsole.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts_web_app/news/urls.py
from django.urls import path

from .views import home, news_war, news_war_show_one, news_prosport, news_prosport_show_one, war_statistic, when_bored


app_name = "news"

urlpatterns = [
    path('', home, name='home'),
    path('news_war/', news_war, name='news_war'),
    path('news_war/<int:_id>', news_war_show_one, name='news_war_show_one'),
    path('news_prosport/', news_prosport, name='news_prosport'),
    path('news_prosport/<int:_id>', news_prosport_show_one, name='news_prosport_show_one'),
    path('war_statistic/', war_statistic, name='war_statistic'),
    path('bored/', when_bored, name='when_bored'),
]

contacts_web_app/news/views.py
import json
from datetime import datetime

from users.views import date_today
import requests
import re

from bs4 import BeautifulSoup

from django.shortcuts import render

from users.models import Avatar


def home(request):
    """
    The home function is the main view of the website. It renders a template
        with information about currency and crypto-currency rates, as well as
        news articles from various sources.

    :param request: Get the request object
    :return: A rendered template
    :doc-author: Trelent
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    currency_info = currency_parse()
    crypto_currency_info = crypto_currency_parse()
    return render(request, "news/index.html", context={'currency_info': currency_info,
                                                       'crypto_currency_info': crypto_currency_info,
                                                       'date': date_today,
                                                       'avatar': avatar})


def news_war(request):
    """
    The news_war function is a view that renders the news_war.html template,
        which displays the short war news from tsn.ua website.

    :param request: Pass the request object to the view
    :return: The news_war
    :doc-author: Trelent
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    short_news = tsn_war_spider()
    return render(request, "news/news_war.html", context={'short_news': short_news,
                                                          'date': date_today,
                                                          'avatar': avatar})


def news_war_show_one(request, _id):
    """
    The news_war_show_one function is used to render the one_news.html template, which displays a single news item
    from the TSN website. The function takes in an id parameter and uses it to find a matching news item from the list of
    shortened news items returned by tsn_war_spider(). If there is no match, then not_found.html will be rendered instead.

    :param request: Get the information about the current user
    :param _id: Get the news item from the list of short news
    :return: A response object
    :doc-author: Trelent
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    short_news = tsn_war_spider()
    news_item = next((item for item in short_news if item['id'] == _id), None)
    if news_item:
        news_details = tsn_page_spider(news_item['href'], news_item['data_src'], news_item['datetime'])
        return render(request, 'news/one_news.html', context={'news_item': news_item,
                                                              'news_details': news_details,
                                                              'date': date_today,
                                                              'avatar': avatar})
    else:
        return render(request, 'news/not_found.html')


def news_prosport(request):
    """
    The news_prosport function is responsible for rendering the news_prosport.html template,
    which displays a list of short news from the prosport.ua website.

    :param request: Get the request object, which contains information about the current web request
    :return: A page with the news_prosport
    :doc-author: Trelent
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    short_news = tsn_prosport_spider()
    return render(request, "news/news_prosport.html", context={'short_news': short_news,
                                                               'date': date_today,
                                                               'avatar': avatar})


def news_prosport_show_one(request, _id):
    """
    The news_prosport_show_one function is used to show one news item from the Prosport website.
        It takes a request and an id as arguments, then it gets the avatar of the user who made this request,
        reads currency info from file, gets short news list from tsn_prosport_spider function and finds a news item with
        given id in this list. If such an item exists it calls tsn_page_spider function to get detailed information about
        this particular article and renders one_prosport_news template with all necessary data.

    :param request: Get the request object, which contains information about the current http request
    :param _id: Identify the news item in the database
    :return: The news_item, which is a dictionary
    :doc-author: Trelent
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    short_news = tsn_prosport_spider()
    news_item = next((item for item in short_news if item['id'] == _id), None)
    if news_item:
        news_details = tsn_page_spider(news_item['href'], news_item['data_src'], news_item['datetime'])
        return render(request, 'news/one_prosport_news.html', context={'news_item': news_item,
                                                                       'news_details': news_details,
                                                                       'date': date_today,
                                                                       'avatar': avatar})
    else:
        return render(request, 'news/not_found.html')


def war_statistic(request):
    """
    The war_statistic function is responsible for parsing the war_statistic.txt file and displaying it on the page.

    :param request: Get the current user
    :return: The war_statistic
    :doc-author: Trelent
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    war_stat = war_stat_parse()
    return render(request, "news/war_statistic.html", context={'war_statistic': war_stat,
                                                               'date': date_today,
                                                               'avatar': avatar})


def when_bored(request):
    """
    The when_bored function is a view that returns the bored.html template, which displays an activity to do when bored.

    :param request: Pass the request object to the view
    :return: A rendered template
    :doc-author: Trelent
    """
    avatar = Avatar.objects.filter(user_id=request.user.id).first()
    url = "https://www.boredapi.com/api/activity/"
    response = requests.get(url).json()
    currency_info = currency_parse()
    crypto_currency_info = crypto_currency_parse()
    return render(request, 'news/index.html', context={'bored': response,
                                                       'currency_info': currency_info,
                                                       'crypto_currency_info': crypto_currency_info,
                                                       'date': date_today,
                                                       'avatar': avatar})


def tsn_war_spider():
    """
    The tsn_war_spider function scrapes the TSN.ua website for news articles related to the war in Ukraine, and returns
    a list of dictionaries containing information about each article.

    :return: A list of dictionaries
    :doc-author: Trelent
    """
    base_url = 'https://tsn.ua/ato'
    response = requests.get(base_url)
    soup = BeautifulSoup(response.text, 'html.parser')
    element = soup.select(
        '.l-page__main.l-sheet.l-sheet__gap .l-flex.l-row .l-gap.l-col.l-col--xl .c-section .l-col.l-col--sm.l-gap')

    news_list = []

    for article in element:
        news_dict = {}

        link = article.find('a', class_='c-card__link')
        id_match = re.search(r'\d+', link['href']) if link else None
        news_dict['id'] = int(id_match.group(0)) if id_match else None

        img = article.find('img', class_='c-card__embed__img')
        news_dict['data_src'] = img['data-src'] if img else None

        link = article.find('a', class_='c-card__link')
        news_dict['href'] = link['href'] if link else None

        title = article.find('h3', class_='c-card__title')
        news_dict['title'] = title.text.strip() if title else None

        time = article.find('time', datetime=True)
        if time:
            datetime_str = time['datetime']
            datetime_obj = datetime.strptime(datetime_str, "%Y-%m-%dT%H:%M:%S%z")
            formatted_datetime = datetime_obj.strftime("%H:%M %d.%m.%Y")
            news_dict['datetime'] = formatted_datetime
        else:
            news_dict['datetime'] = None

        if news_dict['id']:
            news_list.append(news_dict)

    return news_list


def tsn_prosport_spider():
    """
    The tsn_prosport_spider function scrapes the TSN Prosport news page and returns a list of dictionaries.
    Each dictionary contains information about one article:
        - href (str): link to the article;
        - id (int): unique identifier of an article;
        - data_src (str): link to the image on the main page;
        - title (str): title of an article;
        - datetime(str) : time when an article was published.

    :return: A list of dictionaries
    :doc-author: Trelent
    """
    base_url = 'https://tsn.ua/prosport'
    response = requests.get(base_url)
    soup = BeautifulSoup(response.text, 'html.parser')
    element = soup.select(
        '.l-page__main.l-sheet .l-sheet__gap .c-section.u-divider--t .l-row.l-flex.u-hide--sdmd .l-col.l-col--xs.l-gap')

    news_list = []

    for article in element:
        link = article.find('a', class_='c-card__link')

        news_dict = {}
        news_dict['href'] = link['href'] if link else None

        id_match = link['href'].split('/')[-1].split('-')[-1].split('.')[0] if news_dict['href'] else None
        news_dict['id'] = int(id_match) if id_match else None

        img = article.find('img', class_='c-card__embed__img')
        news_dict['data_src'] = img['data-src'] if img else None

        title = article.find('h3', class_='c-card__title')
        news_dict['title'] = title.text.strip() if title else None

contacts_web_app/news/templates/news/index.html
{% extends 'users/base.html' %}

{% block content %}
{% load static %}
{% if user.is_authenticated %}
<br>
<div class="text-center">
    <a href="{% url 'news:home' %}" class="btn btn-primary" style="width: 24%">Home</a>
    <a href="{% url 'news:news_war' %}" class="btn btn-primary" style="width: 24%">War</a>
    <a href="{% url 'news:news_prosport' %}" class="btn btn-primary" style="width: 24%">Sport</a>
    <a href="{% url 'news:war_statistic' %}" class="btn btn-primary" style="width: 24%">War statistics</a>
</div>
<br>
<h1 class="text-center"><b>NEWS</b></h1>
<br>
<div class="row">
    <div class="col-md-3">
        <div class="currency-block">
            <h4>Currency exchange rates on {{ date }}</h4>
            <table class="table-1">
                <thead>
                <tr>
                    <th><img src="{% static 'users/img/currency.png' %}" alt="city"
                             style="width: 40px; height: 40px;"></th>
                    <th>Purchase</th>
                    <th>Sale</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>USD</td>
                    <td>{{ currency_info.currency_USD.purchaseRate }}</td>
                    <td>{{ currency_info.currency_USD.saleRate }}</td>
                </tr>
                <tr>
                    <td>EUR</td>
                    <td>{{ currency_info.currency_EUR.purchaseRate }}</td>
                    <td>{{ currency_info.currency_EUR.saleRate }}</td>
                </tr>
                <tr>
                    <td>PLN</td>
                    <td>{{ currency_info.currency_PLN.purchaseRate }}</td>
                    <td>{{ currency_info.currency_PLN.saleRate }}</td>
                </tr>
                <tr>
                    <td>GBP</td>
                    <td>{{ currency_info.currency_GBP.purchaseRate }}</td>
                    <td>{{ currency_info.currency_GBP.saleRate }}</td>
                </tr>
                <tr>
                    <td>CZK</td>
                    <td>{{ currency_info.currency_CZK.purchaseRate }}</td>
                    <td>{{ currency_info.currency_CZK.saleRate }}</td>
                </tr>
                <tr>
                    <td>JPY</td>
                    <td>{{ currency_info.currency_JPY.purchaseRateNB }}</td>
                    <td>{{ currency_info.currency_JPY.saleRateNB }}</td>
                </tr>
                <tr>
                    <td>MDL</td>
                    <td>{{ currency_info.currency_MDL.purchaseRateNB }}</td>
                    <td>{{ currency_info.currency_MDL.saleRateNB }}</td>
                </tr>
                <tr>
                    <td>CHF</td>
                    <td>{{ currency_info.currency_CHF.purchaseRate }}</td>
                    <td>{{ currency_info.currency_CHF.saleRate }}</td>
                </tr>
                <tr>
                    <td>CAD</td>
                    <td>{{ currency_info.currency_CAD.purchaseRateNB }}</td>
                    <td>{{ currency_info.currency_CAD.saleRateNB }}</td>
                </tr>
                <tr>
                    <td>DKK</td>
                    <td>{{ currency_info.currency_DKK.purchaseRateNB }}</td>
                    <td>{{ currency_info.currency_DKK.saleRateNB }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-md-3">
        <div class="currency-block">
            <h4>Crypto currency rates on {{ date }}</h4>
            <table class="table-1">
                <thead>
                <tr>
                    <th><img src="{% static 'users/img/crypto.png' %}" alt="city"
                             style="width: 40px; height: 40px;"></th>
                    <th>Rate (USD)</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>BTC</td>
                    <td>{{ crypto_currency_info.currency_BTC }}</td>
                </tr>
                <tr>
                    <td>ETH</td>
                    <td>{{ crypto_currency_info.currency_ETH }}</td>
                </tr>
                <tr>
                    <td>BNB</td>
                    <td>{{ crypto_currency_info.currency_BNB }}</td>
                </tr>
                <tr>
                    <td>XRP</td>
                    <td>{{ crypto_currency_info.currency_XRP }}</td>
                </tr>
                <tr>
                    <td>ADA</td>
                    <td>{{ crypto_currency_info.currency_ADA }}</td>
                </tr>
                <tr>
                    <td>DOGE</td>
                    <td>{{ crypto_currency_info.currency_DOGE }}</td>
                </tr>
                <tr>
                    <td>SOL</td>
                    <td>{{ crypto_currency_info.currency_SOL }}</td>
                </tr>
                <tr>
                    <td>MATIC</td>
                    <td>{{ crypto_currency_info.currency_MATIC }}</td>
                </tr>
                <tr>
                    <td>TRX</td>
                    <td>{{ crypto_currency_info.currency_TRX }}</td>
                </tr>
                <tr>
                    <td>LTC</td>
                    <td>{{ crypto_currency_info.currency_LTC }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-md-6">
        <div class="text-center">
            <div class="chat-form">
                <form id="question-form" action="{% url 'news:when_bored' %}" method="post">
                    {% csrf_token %}
                    <br>
                    <br>
                    <div class="mb-2">
                        <label for="question" style="font-weight: bold;">Are you bored? We can help you! Click the button and find out what you can do!</label>
                    </div>
                    <div class="d-flex justify-content-center">
                        <input type="submit" class="btn btn-dark" value="Surprise me!">
                    </div>
                </form>
                <br>
                <div id="response-container"></div>
            </div>
            <div id="question-response">
                {{ bored.activity }}
            </div>
        </div>
    </div>
</div>
<script>
  $(document).ready(function() {
    $('#question-form').submit(function(event) {
      event.preventDefault();
      var form = $(this);
      var url = form.attr('action');
      var formData = form.serialize();

      $.ajax({
        type: 'POST',
        url: url,
        data: formData,
        success: function(response) {
          $('#response-container').html(response);
        }
      });
    });
  });




</script>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}

contacts_web_app/news/templates/news/news_prosport.html
{% extends 'users/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<br>
<div class="text-center">
    <a href="{% url 'news:home' %}" class="btn btn-primary" style="width: 24%">Home</a>
    <a href="{% url 'news:news_war' %}" class="btn btn-primary" style="width: 24%">War</a>
    <a href="{% url 'news:news_prosport' %}" class="btn btn-primary" style="width: 24%">Sport</a>
    <a href="{% url 'news:war_statistic' %}" class="btn btn-primary" style="width: 24%">War statistics</a>
</div>
<div class="news">
    <br>
    <h2>Sport in the World</h2>
    <div class="news-row">
        {% for new in short_news %}
        <div class="news-item">
            <div class="card" style="width: 20rem;">
                <br>
                <img src="{{ new.data_src }}" class="card-img-top" alt="{{ new.title }}" style="width: 18rem; display: block; margin-left: auto; margin-right: auto;">
                <div class="card-body">
                    <a href="{% url 'news:news_prosport_show_one' new.id %}">
                        <p class="card-text">{{ new.title|truncatechars:50 }}</p>
                    </a>
                    <p class="datetime">{{ new.datetime }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}

contacts_web_app/news/templates/news/news_war.html
{% extends 'users/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<div xmlns="http://www.w3.org/1999/html">

    <br>
    <div class="text-center">
        <a href="{% url 'news:home' %}" class="btn btn-primary" style="width: 24%">Home</a>
        <a href="{% url 'news:news_war' %}" class="btn btn-primary" style="width: 24%">War</a>
        <a href="{% url 'news:news_prosport' %}" class="btn btn-primary" style="width: 24%">Sport</a>
        <a href="{% url 'news:war_statistic' %}" class="btn btn-primary" style="width: 24%">War statistics</a>
    </div>
    <div class="news">
        <br>
        <h2>War in Ukraine</h2>
        <div class="news-row">
            {% for new in short_news %}
            <div class="news-item">

                <div class="card" style="width: 20rem;">
                    <br>
                    <img src="{{ new.data_src }}" class="card-img-top" alt="{{ new.title }}" style="width: 18rem; display: block; margin-left: auto; margin-right: auto;">

                    <div class="card-body">
                        <a href="{% url 'news:news_war_show_one' new.id %}">
                            <p class="card-text">{{ new.title|truncatechars:50 }}</p>
                        </a>
                        <p class="datetime">{{ new.datetime }}</p>

                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}

contacts_web_app/news/templates/news/not_found.html
{% extends 'users/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<br>
<div class="text-center">
    <a href="{% url 'news:home' %}" class="btn btn-primary" style="width: 24%">Home</a>
    <a href="{% url 'news:news_war' %}" class="btn btn-primary" style="width: 24%">War</a>
    <a href="{% url 'news:news_prosport' %}" class="btn btn-primary" style="width: 24%">Sport</a>
    <a href="{% url 'news:war_statistic' %}" class="btn btn-primary" style="width: 24%">War statistics</a>
</div>

<div class="not-found-container">
    <h1 class="not-found-heading">404 NOT FOUND</h1>
</div>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}

contacts_web_app/news/templates/news/one_news.html
{% extends 'users/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<br>
<div class="text-center">
    <a href="{% url 'news:home' %}" class="btn btn-primary" style="width: 24%">Home</a>
    <a href="{% url 'news:news_war' %}" class="btn btn-primary" style="width: 24%">War</a>
    <a href="{% url 'news:news_prosport' %}" class="btn btn-primary" style="width: 24%">Sport</a>
    <a href="{% url 'news:war_statistic' %}" class="btn btn-primary" style="width: 24%">War statistics</a>
</div>

<br>
<div class="card" style="width: 60rem;">
    <div class="card-body">
        <img src="{{ news_details.src_img }}" alt="{{ news_details.title }}" class="news-image">
        <br>
        <br>
        <h5 class="card-title">{{ news_details.head_content }}</h5>
        <p class="card-text">{{ news_details.content }}</p>
    </div>
</div>


<!--<div class="news-details">-->
<!--    <img src="{{ news_details.src_img }}" alt="{{ news_details.title }}" class="news-image">-->
<!--    <h3 class="news-title">{{ news_details.head_content }}</h3>-->
<!--    <p class="news-content">{{ news_details.content }}</p>-->
<!--    <p class="news-date">{{ news_details.news_date }}</p>-->
<!--</div>-->
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}

contacts_web_app/news/templates/news/one_prosport_news.html
{% extends 'users/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<br>
    <div class="text-center">
    <a href="{% url 'news:home' %}" class="btn btn-primary" style="width: 24%">Home</a>
    <a href="{% url 'news:news_war' %}" class="btn btn-primary" style="width: 24%">War</a>
    <a href="{% url 'news:news_prosport' %}" class="btn btn-primary" style="width: 24%">Sport</a>
    <a href="{% url 'news:war_statistic' %}" class="btn btn-primary" style="width: 24%">War statistics</a>
    </div>

<br>
<div class="card" style="width: 60rem;">
    <div class="card-body">
        <img src="{{ news_details.src_img }}" alt="{{ news_details.title }}" class="news-image">
        <br>
        <br>
        <h5 class="card-title">{{ news_details.head_content }}</h5>
        <p class="card-text">{{ news_details.content }}</p>
    </div>
</div>
{% else %}
    <div style="text-align: center;">
        <h2>Sign up or login to your account!</h2>
    </div>
{% endif %}
{% endblock %}